"""add active field to sensor model

Revision ID: 5b85731e0b59
Revises: b67cdbf14f2f
Create Date: 2025-07-15 22:02:20.385905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b85731e0b59'
down_revision: Union[str, Sequence[str], None] = 'b67cdbf14f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'active')
    # ### end Alembic commands ###
