"""add data field

Revision ID: b67cdbf14f2f
Revises: f602de6c18ef
Create Date: 2025-07-15 20:45:38.024923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67cdbf14f2f'
down_revision: Union[str, Sequence[str], None] = 'f602de6c18ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'data')
    # ### end Alembic commands ###
